const sketches = [
    {
      title: "Bubble Class",
      folder: "p5/bubble_class",
      thumbnail: "p5/bubble_class/bubble_class_thumbnail.png",
      alt: "Drag mouse to make bubbles! Using Classes",
      tags: ["interactive", "classes", "mouse", "example", "b&w"],
    },
    {
      title: "Example Coordinates",
      folder: "p5/example_coordinates",
      thumbnail: "p5/example_coordinates/example_coordinates_thumbnail.png",
      alt: "Interactive demonstration of X,Y mouse coordinates",
      tags: ["interactive", "classes", "mouse", "example", "coordinates"],
    },
    {
      title: "Peach Grid",
      folder: "p5/example_peach_grid",
      thumbnail: "p5/example_peach_grid/example_peach_grid_thumbnail.png",
      alt: "Generative grid with peach-colored palette",
      tags: ["random", "generative", "color", "grid"],
    },
    {
      title: "Random Lines",
      folder: "p5/example_random_lines",
      thumbnail: "p5/example_random_lines/example_random_lines_thumbnail.png",
      alt: "Randomly placed lines across the canvas",
      tags: ["random", "example", "line", "lines", "generative", "b&w"],
    },
    {
      title: "Sine Wave",
      folder: "p5/example_sinewave",
      thumbnail: "p5/example_sinewave/example_sinewave_thumbnail.png",
      alt: "Animated sine wave visual",
      tags: ["sin", "sine", "generative", "b&w"],
    },
    {
      title: "Genuary 25: Isometric",
      folder: "p5/genuary_25_iso",
      thumbnail: "p5/genuary_25_iso/genuary_25_iso_thumbnail.png",
      alt: "Isometric artwork for Genuary 25",
      tags: ["grid", "genuary", "isometric", "3D", "webgl", "cube", "cubes", "b&w"],
    },
    {
      title: "Genuary 25: Lines",
      folder: "p5/genuary_25_lines",
      thumbnail: "p5/genuary_25_lines/genuary_25_lines_thumbnail.png",
      alt: "Line-based artwork for Genuary 25",
      tags: ["genuary", "webcam", "interactive", "b&w"],
    },
    {
      title: "New News",
      folder: "p5/new_news",
      thumbnail: "p5/new_news/new_news_thumbnail.png",
      alt: "Generative visualization based on headlines",
      tags: ["generative", "interactive", "images", "grid", "random"],
    },
    {
      title: "Touch Bubble",
      folder: "p5/touch_bubble",
      thumbnail: "p5/touch_bubble/touch_bubble_thumbnail.png",
      alt: "Touch interactive bubble sketch",
      tags: ["interactive", "mouse", "soundplay"],
    },
  ];
  